/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0i5Ndzc
 */
import { Button } from "@/components/ui/button"

export function buttonsPage() {
  return (
    (<div className="grid grid-cols-2 gap-6 p-8 h-screen bg-gray-900">
      <div className="flex justify-center items-center space-x-4">
        <Button className="bg-red-600 text-white w-auto px-4 py-2 rounded-full">Default</Button>
        <Button
          className="bg-red-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 w-auto px-4 py-2 rounded-full">
          Focus
        </Button>
        <Button
          className="bg-red-600 opacity-50 cursor-not-allowed w-auto px-4 py-2 rounded-full">Disable</Button>
      </div>
      <div className="flex justify-center items-center space-x-4">
        <Button className="bg-yellow-400 text-gray-800 w-auto px-4 py-2 rounded-full">Default</Button>
        <Button
          className="bg-yellow-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-500 w-auto px-4 py-2 rounded-full">
          Focus
        </Button>
        <Button
          className="bg-yellow-400 opacity-50 cursor-not-allowed w-auto px-4 py-2 rounded-full">Disable</Button>
      </div>
      <div className="flex justify-center items-center space-x-4">
        <Button className="bg-green-600 text-white w-auto px-4 py-2 rounded-full">Default</Button>
        <Button
          className="bg-green-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 w-auto px-4 py-2 rounded-full">
          Focus
        </Button>
        <Button
          className="bg-green-600 opacity-50 cursor-not-allowed w-auto px-4 py-2 rounded-full">Disable</Button>
      </div>
      <div className="flex justify-center items-center space-x-4">
        <Button className="bg-blue-600 text-white w-auto px-4 py-2 rounded-full">Default</Button>
        <Button
          className="bg-blue-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 w-auto px-4 py-2 rounded-full">
          Focus
        </Button>
        <Button
          className="bg-blue-600 opacity-50 cursor-not-allowed w-auto px-4 py-2 rounded-full">Disable</Button>
      </div>
      <div className="flex justify-center items-center space-x-4">
        <Button className="bg-purple-600 text-white w-auto px-4 py-2 rounded-full">Default</Button>
        <Button
          className="bg-purple-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500 w-auto px-4 py-2 rounded-full">
          Focus
        </Button>
        <Button
          className="bg-purple-600 opacity-50 cursor-not-allowed w-auto px-4 py-2 rounded-full">Disable</Button>
      </div>
      <div className="flex justify-center items-center space-x-4">
        <Button className="bg-pink-600 text-white w-auto px-4 py-2 rounded-full">Default</Button>
        <Button
          className="bg-pink-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-pink-500 w-auto px-4 py-2 rounded-full">
          Focus
        </Button>
        <Button
          className="bg-pink-600 opacity-50 cursor-not-allowed w-auto px-4 py-2 rounded-full">Disable</Button>
      </div>
      <div className="flex justify-center items-center space-x-4">
        <Button className="bg-gray-600 text-white w-auto px-4 py-2 rounded-full">Default</Button>
        <Button
          className="bg-gray-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 w-auto px-4 py-2 rounded-full">
          Focus
        </Button>
        <Button
          className="bg-gray-600 opacity-50 cursor-not-allowed w-auto px-4 py-2 rounded-full">Disable</Button>
      </div>
      <div className="flex justify-center items-center space-x-4">
        <Button className="bg-orange-400 text-gray-800 w-auto px-4 py-2 rounded-full">Default</Button>
        <Button
          className="bg-orange-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-orange-500 w-auto px-4 py-2 rounded-full">
          Focus
        </Button>
        <Button
          className="bg-orange-400 opacity-50 cursor-not-allowed w-auto px-4 py-2 rounded-full">Disable</Button>
      </div>
      <div className="flex justify-center items-center space-x-4">
        <Button className="bg-teal-600 text-white w-auto px-4 py-2 rounded-full">Default</Button>
        <Button
          className="bg-teal-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500 w-auto px-4 py-2 rounded-full">
          Focus
        </Button>
        <Button
          className="bg-teal-600 opacity-50 cursor-not-allowed w-auto px-4 py-2 rounded-full">Disable</Button>
      </div>
      <div className="flex justify-center items-center space-x-4">
        <Button className="bg-cyan-600 text-white w-auto px-4 py-2 rounded-full">Default</Button>
        <Button
          className="bg-cyan-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500 w-auto px-4 py-2 rounded-full">
          Focus
        </Button>
        <Button
          className="bg-cyan-600 opacity-50 cursor-not-allowed w-auto px-4 py-2 rounded-full">Disable</Button>
      </div>
      <div className="flex justify-center items-center space-x-4">
        <Button className="bg-lime-400 text-gray-800 w-auto px-4 py-2 rounded-full">Default</Button>
        <Button
          className="bg-lime-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-lime-500 w-auto px-4 py-2 rounded-full">
          Focus
        </Button>
        <Button
          className="bg-lime-400 opacity-50 cursor-not-allowed w-auto px-4 py-2 rounded-full">Disable</Button>
      </div>
      <div className="flex justify-center items-center space-x-4">
        <Button className="bg-fuchsia-600 text-white w-auto px-4 py-2 rounded-full">Default</Button>
        <Button
          className="bg-fuchsia-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-fuchsia-500 w-auto px-4 py-2 rounded-full">
          Focus
        </Button>
        <Button
          className="bg-fuchsia-600 opacity-50 cursor-not-allowed w-auto px-4 py-2 rounded-full">Disable</Button>
      </div>
    </div>)
  );
}
